language: c
compiler:
  - gcc
before_install:
 - sudo apt-get install python-pip
 - sudo pip install xml2rfc

# Change this to your needs
script: 
  - ./createdrafts.sh


after_success: ./update_pages.sh
